1 REM *** INPUT HANDLING TEST ***
2 REM *** THIS TEST REQUIRES MANUAL INPUT ***
10 PRINT "=== INPUT HANDLING ==="
20 PRINT "NUMERIC INPUT PROMPT"
30 PRINT "ENTER 42:"
40 INPUT X
50 PRINT "YOU ENTERED:";X
60 PRINT "STRING INPUT PROMPT"
70 PRINT "ENTER HELLO:"
80 INPUT A$
90 PRINT "YOU ENTERED:";A$
100 PRINT "PROMPTED INPUT:"
110 INPUT "ENTER A NUMBER";N
120 PRINT "N=";N
130 PRINT "=== END INPUT HANDLING ==="
140 END
